version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - mvn install -DskipTests
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/cicd.jar
  discard-paths: yes
